### ISSUE TITLE
[FEAT] Navigation 컴포넌트 구현

### ISSUE THREAD

**Issue by who0803** [Fasoo-LLM-Chat-UI-UX/llmchat-frontend#1]
## 📝 Description
내비게이션 컴포넌트구현

## ✔️ To-do
- [x] Navigation 컴포넌트 구현
- [x] NavigationSearch 컴포넌트 구현
- [x] HistoryList 컴포넌트 구현
- [x] HistoryItem 컴포넌트 구현

## ⚠️ ETC
- 기능은 추후 구현
- 설정 모달 추후 구현
