### ISSUE TITLE
[FEAT] 메인컨텐츠 챗 컴포넌트 구현

### ISSUE THREAD

**Issue by sooocong** [Fasoo-LLM-Chat-UI-UX/llmchat-frontend#2]
## 📝 Description
- 메인페이지의 챗 컴포넌트 구현

## ✔️ To-do
- [x] 질문 컴포넌트 UI 구현
- [x] 답변 컴포넌트 UI 구현
- [x] 아이콘 리스트 컴포넌트 구현
- [x] ChatInput 컴포넌트 UI 구현

## ⚠️ ETC
- 세부 기능은 추후 구현 예정입니다.
