### ISSUE TITLE
[FEAT] Mainpage Icon 기능 연결

### ISSUE THREAD

**Issue by sooocong** [Fasoo-LLM-Chat-UI-UX/llmchat-frontend#6]
## 📝 Description

- 메인페이지의 각 아이콘 클릭시 원하는 동작이 수행될 수 있도록 구현할 예정입니다.

## ✔️ To-do

- [x] 답변 컴포넌트 - speakerIcon 동작 구현
- [x] 답변 컴포넌트 - copyIcon 동작 구현
- [x] 답변 컴포넌트 - reanswerIcon 동작 구현
- [x] 답변 컴포넌트 - shareIcon 동작 구현
- [x] 답변 컴포넌트 - goodIcon 동작 구현
- [x] 답변 컴포넌트 - badIcon 동작 구현
- [x] 챗 컴포넌트 - sendIcon 동작 구현

## ⚠️ ETC

- 기타사항, To reviewers
